"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Bot, Camera, Check, Globe2, ImagePlus, Megaphone, MessageSquareText, Plus, Radio, Save, Send, Sparkles, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Profile={name:string;username:string;description:string;avatarKey:string|null};
type Command={id:number;command:string;description:string;response:string};
type News={id:number;title:string;body:string;status:"draft"|"published";createdAt:string};
type Connection={channel:"telegram"|"whatsapp"|"instagram"|"webchat";status:"not_connected"|"setup_required"|"pending_confirmation"|"connected"|"error";externalAccountId:string|null;externalUsername:string|null;onboardingUrl:string|null};
type StudioData={profile:Profile;commands:Command[];news:News[];connections:Connection[]};
const initial:StudioData={profile:{name:"Мой первый бот",username:"my_first_bot",description:"Отвечает на вопросы и делится новостями.",avatarKey:null},commands:[],news:[],connections:["telegram","whatsapp","instagram","webchat"].map(channel=>({channel,status:"not_connected",externalAccountId:null,externalUsername:null,onboardingUrl:null})) as Connection[]};

export default function Home(){
 const [data,setData]=useState(initial),[busy,setBusy]=useState(false),[notice,setNotice]=useState("Все изменения сохраняются");
 const [tab,setTab]=useState("profile");
 const [cmd,setCmd]=useState({command:"start",description:"Начать работу",response:"Привет! Я готов помочь. Выберите команду ниже."});
 const [post,setPost]=useState({title:"",body:""});
 useEffect(()=>{fetch("/api/studio").then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>setNotice("Рабочее пространство временно недоступно"));},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:Record<string,unknown>,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:Record<string,unknown>)=>Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined);void register({name:"create_bot_command",title:"Добавить команду",description:"Добавляет команду и ответ в текущего бота.",inputSchema:{type:"object",properties:{command:{type:"string"},description:{type:"string"},response:{type:"string"}},required:["command","response"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const value=input as {command:string;description?:string;response:string};const result=await action({action:"addCommand",command:{command:value.command,description:value.description||"",response:value.response}});return{saved:!!result}}});void register({name:"publish_bot_news",title:"Опубликовать новость",description:"Создаёт опубликованную новость для текущего бота.",inputSchema:{type:"object",properties:{title:{type:"string"},body:{type:"string"}},required:["title","body"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const value=input as {title:string;body:string};const result=await action({action:"addNews",news:{title:value.title,body:value.body,status:"published"}});return{published:!!result}}});return()=>lifecycle.abort();},[]);
 const progress=useMemo(()=>35+(data.profile.avatarKey?15:0)+(data.commands.length?20:0)+(data.news.some(n=>n.status==="published")?10:0)+(data.connections.some(c=>c.status==="connected")?20:0),[data]);
 async function action(payload:Record<string,unknown>){setBusy(true);const r=await fetch("/api/studio",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const out=await r.json() as StudioData&{error?:string};setBusy(false);if(!r.ok){setNotice(out.error||"Не удалось сохранить");return null}setData(out);setNotice("Сохранено");return out}
 async function prepareTelegram(){const out=await action({action:"prepareChannel",channel:"telegram"});const connection=out?.connections.find(c=>c.channel==="telegram");if(connection?.onboardingUrl){window.location.href=connection.onboardingUrl;return}setNotice("Сначала подключим центрального Manager Bot")}
 async function upload(file?:File){if(!file)return;if(!file.type.startsWith("image/")||file.size>4*1024*1024){setNotice("Выберите изображение до 4 МБ");return}setBusy(true);const form=new FormData();form.append("avatar",file);const r=await fetch("/api/avatar",{method:"POST",body:form});const out=await r.json() as {avatarKey?:string;error?:string};setBusy(false);if(!r.ok||!out.avatarKey){setNotice(out.error||"Не удалось загрузить картинку");return}setData(v=>({...v,profile:{...v.profile,avatarKey:out.avatarKey!}}));setNotice("Картинка загружена")}
 const published=data.news.find(n=>n.status==="published"),avatar=data.profile.avatarKey?`/api/avatar?v=${encodeURIComponent(data.profile.avatarKey)}`:null;
 return <main className="min-h-screen bg-[#f3f1ea] text-[#18332e]">
  <header className="sticky top-0 z-20 border-b border-[#18332e]/10 bg-[#f3f1ea]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-4 sm:px-7">
   <Link href="/" className="flex items-center gap-3 text-inherit no-underline"><span className="grid size-9 place-items-center rounded-xl bg-[#18332e] text-[#f7d75d]"><Bot className="size-5"/></span><div><p className="font-semibold leading-none">Bot Studio</p><p className="mt-1 text-xs text-[#57706a]">Конструктор Telegram-ботов</p></div></Link>
   <div className="flex items-center gap-3"><span className="hidden text-sm text-[#57706a] sm:block">{busy?"Сохраняю…":notice}</span><Button className="rounded-full px-5" onClick={()=>setTab("channels")}><Radio/>Подключить канал</Button></div>
  </div></header>
  <div className="mx-auto grid max-w-[1440px] gap-5 p-4 sm:p-7 lg:grid-cols-[220px_minmax(0,1fr)_340px]">
   <aside className="rounded-[24px] bg-[#18332e] p-4 text-[#d9e5df] lg:sticky lg:top-[92px] lg:h-[calc(100vh-120px)]">
    <div className="mb-7 rounded-2xl bg-white/8 p-4"><div className="mb-3 flex justify-between text-xs text-[#a9beb7]"><span>Готовность</span><span>{progress}%</span></div><div className="h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#f7d75d] transition-all" style={{width:`${progress}%`}}/></div></div>
    <nav className="space-y-1 text-sm"><Nav icon={Bot} text="Профиль бота" done/><Nav icon={MessageSquareText} text="Команды" done={!!data.commands.length}/><Nav icon={Megaphone} text="Новости" done={!!data.news.length}/><Nav icon={Globe2} text="Каналы" done={data.connections.some(c=>c.status==="connected")}/></nav>
    <p className="mt-6 border-t border-white/10 pt-5 text-xs leading-relaxed text-[#a9beb7]">Сначала настройте внешний вид, затем добавьте команды и первую новость.</p>
   </aside>
   <section className="min-w-0 rounded-[28px] border border-[#18332e]/10 bg-[#fffdf8] p-5 shadow-[0_20px_60px_rgba(24,51,46,.06)] sm:p-8">
    <div className="mb-7 flex items-start justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.16em] text-[#e2533f]">Рабочее пространство</p><h1 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Создайте первого бота</h1><p className="mt-2 text-[#61736f]">Профиль, ответы на команды и новости — в одном месте.</p></div><Sparkles className="hidden text-[#e2533f] sm:block"/></div>
    <Tabs value={tab} onValueChange={setTab} className="gap-6"><TabsList className="grid h-auto w-full grid-cols-4 rounded-2xl bg-[#eef0e9] p-1"><TabsTrigger value="profile" className="h-11 rounded-xl">Профиль</TabsTrigger><TabsTrigger value="commands" className="h-11 rounded-xl">Команды <Count n={data.commands.length}/></TabsTrigger><TabsTrigger value="news" className="h-11 rounded-xl">Новости <Count n={data.news.length}/></TabsTrigger><TabsTrigger value="channels" className="h-11 rounded-xl">Каналы</TabsTrigger></TabsList>
     <TabsContent value="profile" className="space-y-6"><div className="grid gap-5 sm:grid-cols-[150px_1fr]">
      <label className="flex aspect-square cursor-pointer flex-col items-center justify-center overflow-hidden rounded-[28px] border-2 border-dashed border-[#18332e]/18 bg-[#f3f1ea] text-center hover:border-[#e2533f]">{avatar?<img src={avatar} alt="Аватар бота" className="h-full w-full object-cover"/>:<><ImagePlus className="mb-2 size-7 text-[#e2533f]"/><b className="text-sm">Картинка</b><span className="mt-1 text-xs text-[#71807d]">до 4 МБ</span></>}<input type="file" accept="image/*" className="sr-only" onChange={e=>upload(e.target.files?.[0])}/></label>
      <div className="space-y-4"><Field label="Название бота"><Input value={data.profile.name} onChange={e=>setData({...data,profile:{...data.profile,name:e.target.value}})} className="h-12 rounded-xl bg-white"/></Field><Field label="Username"><div className="relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-[#71807d]">@</span><Input value={data.profile.username} onChange={e=>setData({...data,profile:{...data.profile,username:e.target.value.replace(/[^a-zA-Z0-9_]/g,"")}})} className="h-12 rounded-xl bg-white pl-8"/></div></Field></div>
     </div><Field label="Описание"><Textarea value={data.profile.description} onChange={e=>setData({...data,profile:{...data.profile,description:e.target.value}})} className="min-h-28 rounded-xl bg-white" maxLength={240}/></Field><Button disabled={busy} onClick={()=>action({action:"saveProfile",profile:data.profile})} className="h-11 rounded-xl bg-[#e2533f] px-5 text-white hover:bg-[#c84432]"><Save/>Сохранить профиль</Button></TabsContent>
     <TabsContent value="commands" className="space-y-5"><Editor title="Новая команда"><div className="grid gap-4 sm:grid-cols-2"><Field label="Команда"><div className="relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-[#71807d]">/</span><Input value={cmd.command} onChange={e=>setCmd({...cmd,command:e.target.value.replace(/[^a-zA-Z0-9_]/g,"")})} className="h-11 rounded-xl bg-white pl-8"/></div></Field><Field label="Подпись"><Input value={cmd.description} onChange={e=>setCmd({...cmd,description:e.target.value})} className="h-11 rounded-xl bg-white"/></Field></div><div className="mt-4"><Field label="Ответ бота"><Textarea value={cmd.response} onChange={e=>setCmd({...cmd,response:e.target.value})} className="min-h-24 rounded-xl bg-white"/></Field></div><Button className="mt-4 h-11 rounded-xl" disabled={busy||!cmd.command||!cmd.response} onClick={()=>action({action:"addCommand",command:cmd}).then(ok=>ok&&setCmd({command:"",description:"",response:""}))}><Plus/>Добавить команду</Button></Editor>
      <div className="space-y-3">{data.commands.length?data.commands.map(x=><article key={x.id} className="flex items-start gap-4 rounded-2xl border border-[#18332e]/10 p-4"><span className="rounded-lg bg-[#f7d75d] px-2.5 py-1 font-mono text-sm font-semibold">/{x.command}</span><div className="min-w-0 flex-1"><p className="font-medium">{x.description||"Без подписи"}</p><p className="mt-1 line-clamp-2 text-sm text-[#61736f]">{x.response}</p></div><IconButton label="Удалить команду" onClick={()=>action({action:"deleteCommand",id:x.id})}/></article>):<Empty icon={MessageSquareText} title="Команд пока нет" text="Добавьте /start — первое сообщение для нового пользователя."/>}</div></TabsContent>
     <TabsContent value="news" className="space-y-5"><Editor title="Новая публикация" sub="Сохраните черновик или сразу опубликуйте новость."><div className="space-y-4"><Field label="Заголовок"><Input value={post.title} onChange={e=>setPost({...post,title:e.target.value})} className="h-11 rounded-xl bg-white" placeholder="Что произошло?"/></Field><Field label="Текст новости"><Textarea value={post.body} onChange={e=>setPost({...post,body:e.target.value})} className="min-h-32 rounded-xl bg-white" placeholder="Напишите коротко и по делу…"/></Field></div><div className="mt-4 flex flex-wrap gap-3"><Button variant="outline" className="h-11 rounded-xl" disabled={busy||!post.title||!post.body} onClick={()=>action({action:"addNews",news:{...post,status:"draft"}}).then(ok=>ok&&setPost({title:"",body:""}))}>Сохранить черновик</Button><Button className="h-11 rounded-xl bg-[#e2533f] text-white hover:bg-[#c84432]" disabled={busy||!post.title||!post.body} onClick={()=>action({action:"addNews",news:{...post,status:"published"}}).then(ok=>ok&&setPost({title:"",body:""}))}><Send/>Опубликовать</Button></div></Editor>
      <div className="space-y-3">{data.news.length?data.news.map(x=><article key={x.id} className="rounded-2xl border border-[#18332e]/10 p-4"><div className="flex items-start justify-between"><div><span className={`mb-2 inline-block rounded-full px-2.5 py-1 text-xs font-medium ${x.status==="published"?"bg-[#dcebe3] text-[#24613d]":"bg-[#eee9d8] text-[#78671e]"}`}>{x.status==="published"?"Опубликовано":"Черновик"}</span><h3 className="font-semibold">{x.title}</h3></div><IconButton label="Удалить новость" onClick={()=>action({action:"deleteNews",id:x.id})}/></div><p className="mt-2 text-sm leading-relaxed text-[#61736f]">{x.body}</p></article>):<Empty icon={Megaphone} title="Новостей пока нет" text="Первая публикация появится здесь и в превью бота."/>}</div></TabsContent>
     <TabsContent value="channels" className="space-y-5"><div><h2 className="text-xl font-semibold">Где будет работать бот</h2><p className="mt-1 text-sm text-[#61736f]">Сценарий создаётся один раз, а адаптеры переводят его на язык каждого канала.</p></div><div className="grid gap-4 sm:grid-cols-2"><ChannelCard title="Telegram" icon={Send} status={data.connections.find(c=>c.channel==="telegram")?.status||"not_connected"} active onClick={prepareTelegram}/><ChannelCard title="WhatsApp" icon={MessageSquareText} status="planned"/><ChannelCard title="Instagram" icon={Camera} status="planned"/><ChannelCard title="Виджет на сайт" icon={Globe2} status="planned"/></div><div className="rounded-2xl bg-[#18332e] p-5 text-white"><p className="text-sm font-semibold text-[#f7d75d]">Архитектура готова к росту</p><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#d9e5df]">Профиль, команды, сценарии и публикации не зависят от Telegram. Новый канал подключается отдельным адаптером, не меняя данные и логику бота.</p></div></TabsContent>
    </Tabs>
   </section>
   <aside className="lg:sticky lg:top-[92px] lg:h-fit"><div className="overflow-hidden rounded-[32px] border-[8px] border-[#18332e] bg-[#e8f0ec] shadow-[0_24px_70px_rgba(24,51,46,.18)]"><div className="flex items-center gap-3 bg-[#fffdf8] p-4"><div className="grid size-11 place-items-center overflow-hidden rounded-full bg-[#e2533f] text-lg font-semibold text-white">{avatar?<img src={avatar} alt="" className="h-full w-full object-cover"/>:(data.profile.name[0]||"Б").toUpperCase()}</div><div><p className="font-semibold">{data.profile.name||"Новый бот"}</p><p className="text-xs text-[#61736f]">бот</p></div></div><div className="min-h-[420px] space-y-3 p-4"><Bubble>{data.profile.description||"Здесь появится описание бота."}</Bubble>{data.commands[0]&&<><Bubble mine>/{data.commands[0].command}</Bubble><Bubble>{data.commands[0].response}</Bubble></>}{published&&<Bubble><b className="mb-1 block text-xs text-[#e2533f]">НОВОСТЬ</b><strong>{published.title}</strong><span className="mt-1 block text-[#61736f]">{published.body}</span></Bubble>}</div><div className="m-3 flex items-center rounded-full bg-white p-2 pl-4 text-sm text-[#82908d]"><span className="flex-1">Сообщение</span><span className="grid size-9 place-items-center rounded-full bg-[#18332e] text-white"><Send className="size-4"/></span></div></div><p className="mt-4 text-center text-xs text-[#71807d]">Живое превью обновляется вместе с настройками</p></aside>
  </div>
 </main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>}
function Nav({icon:Icon,text,done}:{icon:typeof Bot;text:string;done:boolean}){return <div className="flex items-center gap-3 rounded-xl px-3 py-3 hover:bg-white/8"><Icon className="size-4"/><span className="flex-1">{text}</span>{done&&<Check className="size-4 text-[#f7d75d]"/>}</div>}
function Count({n}:{n:number}){return <span className="rounded-full bg-[#18332e]/8 px-2 py-0.5 text-xs">{n}</span>}
function Editor({title,sub,children}:{title:string;sub?:string;children:React.ReactNode}){return <div className="rounded-2xl border border-[#18332e]/10 bg-[#f5f5ef] p-5"><h2 className="text-lg font-semibold">{title}</h2>{sub&&<p className="mb-4 text-sm text-[#61736f]">{sub}</p>}{!sub&&<div className="h-4"/>}{children}</div>}
function IconButton({label,onClick}:{label:string;onClick:()=>void}){return <Button size="icon-sm" variant="ghost" aria-label={label} onClick={onClick}><Trash2/></Button>}
function Empty({icon:Icon,title,text}:{icon:typeof Bot;title:string;text:string}){return <div className="rounded-2xl border border-dashed border-[#18332e]/18 p-8 text-center"><Icon className="mx-auto mb-3 size-7 text-[#e2533f]"/><p className="font-semibold">{title}</p><p className="mx-auto mt-1 max-w-sm text-sm text-[#61736f]">{text}</p></div>}
function Bubble({children,mine=false}:{children:React.ReactNode;mine?:boolean}){return <div className={`${mine?"ml-9 rounded-tr-md bg-[#d9f5cf]":"mr-9 rounded-tl-md bg-white"} rounded-2xl p-3 text-sm shadow-sm`}>{children}<span className="mt-2 block text-right text-[11px] text-[#83938f]">10:24</span></div>}
function ChannelCard({title,icon:Icon,status,active=false,onClick}:{title:string;icon:typeof Bot;status:string;active?:boolean;onClick?:()=>void}){const labels:Record<string,string>={not_connected:"Не подключён",setup_required:"Нужен Manager Bot",pending_confirmation:"Ожидает подтверждения",connected:"Подключён",error:"Нужно повторить",planned:"Скоро"};return <article className={`rounded-2xl border p-5 ${active?"border-[#e2533f]/35 bg-[#fff8f5]":"border-[#18332e]/10 bg-[#f5f5ef]"}`}><div className="flex items-start justify-between"><span className={`grid size-11 place-items-center rounded-xl ${active?"bg-[#e2533f] text-white":"bg-[#18332e]/8 text-[#61736f]"}`}><Icon className="size-5"/></span><span className="rounded-full bg-white px-2.5 py-1 text-xs text-[#61736f]">{labels[status]||status}</span></div><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 text-sm text-[#61736f]">{active?"Автоматическое создание через Telegram Managed Bots.":"Подключим следующим адаптером."}</p>{active&&<Button className="mt-4 h-10 w-full rounded-xl" onClick={onClick}>{status==="pending_confirmation"?"Продолжить в Telegram":"Подготовить подключение"}</Button>}</article>}
